### PR TITLE
Remove MQTTClient.h

### PR DESCRIPTION
**Pull request by georgepoenaru**
Using frameworks in Podfile you get this error: 

"Include of non-modular header inside framework module 'MQTTClient.MQTTClient'"

However you don't need tho pack classes in MQTTClient.h because we can just use import:

@import MQTTClient;

### CODE REVIEW

**Comment by andreamazz** [comment]
Any news on this?
I'm trying to integrate this pod as a dependency in another swift pod, but this header generates compile errors.

Thanks

**Comment by ckrey** [comment]
I tried to recreate the problem by setting up a test project `MQTTSwift`in this repo.
I don't see the problem. Can you recreate the problem using the test project?
I am using Cocoapods 1.0.0

**Comment by georgepoenaru** [comment]
This problem only appear when you add MQTT Client as dependency in the podspec file of a swift framework. 

Try to create a swift framework that use MQTT Client, add that swift framework to an ObjC or Swift project through a Podfile and you'll find the problem.

I resolved this problem by making MQTTClient.h private in the current podspec: 

mqttc.subspec 'Core' do |core|
		core.source_files =	'MDKMQTTClient/MQTTClient/*.{h,m}'
		core.private_header_files = 'MDKMQTTClient/MQTTClient/MQTTClient.h'
		core.dependency 'CocoaLumberjack'
end

**Comment by ckrey** [comment]
The problem is now resolved in

**Pull request closed without merging**
