### PR TITLE
Adds -[MQTTSessionManagerDelegate sessionManager:didChangeState:]

### PR DESCRIPTION
**Pull request by JakeSc**
Fixes https://github.com/ckrey/MQTT-Client-Framework/issues/222.

### CODE REVIEW

**Comment by JakeSc** [comment]
I'm seeing this callback getting called many times for each session. Here is an example of what happens when I launch my app, subscribe to one topic, and connect:
```
didChangeState: Connecting
didChangeState: Connected
didChangeState: Connecting
didChangeState: Connecting
didChangeState: Connecting
didChangeState: Connecting
didChangeState: Connecting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Closed
didChangeState: Starting
didChangeState: Connected
```
Perhaps soon I'll add an `if newState == oldState, return` guard to suppress some of these.

**Comment by ckrey** [comment]
would you print the session.host, etc. with each didChangeState please? I think there is more than one session started at the same time. And they seem to get errors when connecting

**Comment by JakeSc** [comment]
You were right @ckrey, thanks for the suggestion. I was indeed instantiating multiple connections. Now with just a single MQTTSessionManager, I'm seeing simply:
```
didChangeState: Connecting
didChangeState: Connected
```

**Comment by JakeSc** [comment]
Hey @ckrey, do you have additional comments on this PR?

**Comment by ckrey** [comment]
Thanks @JakeSc

**Pull request merged**
