### PR TITLE
Add SSL Certificates Pinning and Self-Signed Certificates support

### PR DESCRIPTION
**Pull request by bobwenx**
## Motivation:
Right now, if SSL is enabled, by default CFStream only evaluate server's certificates using CA infrastructure, and for most case, this type of check is enough. 

However, if target app using security model which require pinning SSL certificates to helps prevent man-in-the-middle attacks and other vulnerabilities. we need to  provide security policy to evaluate server trust against pinned X.509 certificates and public keys over secure connections. 

Plus, if target app try to using self-signed certificates In CA infrastructure:
   Target app may establish a SSL/TLS connection with server which using self-signed certificates by install the certificates into OS keychain(either programmatically or manually). however, this method has some disadvantages:
 * every socket target app created will trust certificates they added.
 * if user choice to remove certificates from keychain, target app need to handling certificates re-adding.

By implements customize certificates verification, we also support self-signed or private CA infrastructure.  Target app are able to verify the cert for the socket they creating and no affect on other sockets.
 
## Modifications:
* Add `MQTTSSLSecurityPolicy` class to evaluate server trust(Modified from AFNetwork).
* Add additional `initWithClientId` method and logical conditions to apply security policy in `MQTTSession` class.
* if security policy is not provided, the code executed as original(using CA infrastructure).
* if security policy is provided, we turn off certificates evaluate in CFStream handshake, and then perform validation during encoder/decoder processing.

## Result:
* All original interface/methods keep same and test code passed.
* Using Self-Signed certificates on client-side is possible.
* Client-side SSL Certificates Pinning is supported(either by using X509 Certificate or Public Key).
* Applications dealing with sensitive customer data or financial information are strongly encouraged to route all communication over an SSL/TLS connection with SSL pinning configured and enabled.
 
## References
* [AFNetwork Security Policy](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFSecurityPolicy.h)
* [Apple Guide: Overriding TLS Chain Validation Correctly](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/OverridingSSLChainValidationCorrectly.html)

### CODE REVIEW

**Comment by bobwenx** [comment]
A example of using Self-Signed certificates with mosquitto server:

* Generate a server key(without encryption) & certificate.
```bash
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.pem
```
* Convert certificate to der format(using by iOS app)
```bash
  openssl x509 -outform der -in server.pem -out server.der
```
* Configuring mosquitto to using generated key & certificate.
```bash
  vi mosquitto.conf

  port 8883
  capath path to conf dir
  # Path to the PEM encoded server certificate.
  certfile server.pem
  # Path to the PEM encoded keyfile.
  keyfile server.key
```
  then start mosquitto using above conf file:
```bash
  mosquitto -c mosquitto.conf
```

* Try to connect to TLS-enabled mosquitto by using server.der  

  * add `server.der` to your project bundle
  * connect to mosquitto over SSL by using `securityPolicy`:

```objective-c
   MQTTSSLSecurityPolicy* securityPolicy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModePublicKey];
   NSString* certificate = [[NSBundle bundleForClass:[self class]] pathForResource:@"server" ofType:@"der"];
   securityPolicy.pinnedCertificates = @[ [NSData dataWithContentsOfFile:certificate] ];
   securityPolicy.allowInvalidCertificates = YES; // we using self-signed certificate and didn't coupled with CA infrastructure
   MQTTSession *session = [[MQTTSession alloc]
                            initWithClientId:@"MQTTOverTLS"
                            userName:@"user"
                            password:@"secret"
                            keepAlive:60
                            cleanSession:YES
                            will:YES
                            willTopic:@"example/status"
                            willMsg:[@"Client off-line" dataUsingEncoding:NSUTF8StringEncoding]
                            willQoS:2
                            willRetainFlag:YES
                            protocolLevel:4
                            runLoop:[NSRunLoop currentRunLoop]
                            forMode:NSRunLoopCommonModes
                            securityPolicy:securityPolicy];
    
    [session connectAndWaitToHost:@"localhost" port:8883 usingSSL:YES];
    // do business...
    [session closeAndWait];
```

**Comment by ckrey** [comment]
Thank you so much for this enhancement. Will review and merge soon

**Comment by ckrey** [comment]
Merged

**Comment by w3hacker** [comment]
@bobwenx hi

Do you know wow does it use with MQTTSessionManager

**Pull request closed without merging**
