### PR TITLE
support for VoIP application

### PR DESCRIPTION
**Pull request by OmidID**
to enable background VoIP application please use `session!.voip = true`
and then connect to server

### CODE REVIEW

**Comment by ckrey** [comment]
@OmidID do you think you would get this through the app store checks. AFAIK they are quite strict when it comes to accepting background modes if the app is not actually an voip app?

I know this would be a way to keep the MQTT connection open all time.

**Comment by wenxin3262** [comment]
If your app is a VoIP app and there is an running VoIP session, your connection won't get killed by iOS system since your app is actually running in the background. I don't think this modification is needed. It is working by default.

**Comment by OmidID** [comment]
@ckrey i know about that but if you use it as a VoIP application it's require to set this option.
Actually there is 2 cases you may need this feature. 1. In real VoIP application 2. Enterprise distribute app.
anyway we have a VoIP application for voice Call and we had used that there

**Comment by OmidID** [comment]
@wenxin3262 exactly after this modification our problem was solved.

**Comment by ziaoang** [comment]
It seems that this method can not work on iOS 10+.
[https://developer.apple.com/library/content/qa/qa1938/_index.html](url)

**Comment by OmidID** [comment]
@ziaoang the link you had sent it's not valid.
but anyway because of the new VOIP push notification this method has been discontinue, so because of the existing application this feature will working without problem.

**Comment by wenxin3262** [comment]
@OmidID his link is valid if you copy not click. Our product uses VoIP in iOS 9 and 10 not experience any issue you mentioned. Again, I think the feature is not needed to develop a VoIP app but might help older iOS versions.

**Comment by OmidID** [comment]
> At some point support for the legacy VoIP architecture will be removed, whereupon all VoIP apps will have to move to the new PushKit-based VoIP architecture. It’s better to start this work sooner rather than later.

@wenxin3262 mmm. you right. but anyway it's not a big deal, i add 10 line of code for maximum as i remember and i think for legacy VoIP architecture it's enough.

**Comment by OmidID** [comment]
i have another idea. we can rename `session!.voip` to `session!.legacyVoip`

**Pull request merged**
