### PR TITLE
Support set log level externally

### PR DESCRIPTION
**Pull request by jcavar**

### CODE REVIEW

**Comment by jcavar** [comment]
Fixes https://github.com/ckrey/MQTT-Client-Framework/issues/330

**Comment by jcavar** [comment]
If you decide to merge this one, Podspec and tag needs update as well.

**Comment by ckrey** [comment]
Thank you @jcavar 

I don't want to accept the pull request as it is because it eliminates the possibility to control the logging level on a per file basis.
On the other hand your suggestion to have only one log level centrally for the library is very good.

Still thinking...

**Comment by jcavar** [comment]
I can revert my changes to `myLogLevel` if that is what you mean? But to be honest, it is not used currently and framework log level should be controlled from application, not from framework file itself.

**Pull request merged**
