### PR TITLE
Fix random crashes on core data persistence

### PR DESCRIPTION
**Pull request by oh6hay**
Main thread accesses the main MOC, only background threads get their own private queue MOCs.

### CODE REVIEW

**Comment by oh6hay** [comment]
I was experiencing random core data related crashes and noticed the MQTTCoreDataPersistence created a private queue MOC and stored it in the thread dictionary for all threads, including the main thread. The insertNewObjectForEntity... and MOC save calls were not consistently accessing the parent (main queue) MOC and the thread-specific private ones.

It's hard to prove the absence of intermittent random crashes, but this change seemed to make the crashes go away.

**Comment by ckrey** [comment]
Thanks for your contribution. 
There was one line missing, causing a deadlock when working with concurrent threads. Fixed

**Comment by oh6hay** [comment]
great, i missed that one then :) Also I’m glad I could help, your MQTTClient is a great piece of software.

ossi

**Comment by BigBugGrow** [comment]
oh6hay，your pull request help me solve my problem,thank you very much!

**Pull request merged**
